[package]
name = "automata"
version = "0.1.0"
authors = ["16yuki0702 <hs19870702@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
